In [1]:
import numpy as np
import pandas as pd
from pydataset import data

In [2]:
pokemon= data('pokemon')

Did you mean:
pneumon, poisons, pension, coleman, apoeapoc, NOxEmissions

In [5]:
pokemon = pd.read_csv(r'/Users/andy.jensen/codeup-data-science/pokemon_data.csv')
pokemon

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [6]:
#dimensions
pokemon.shape

(800, 12)

In [7]:
#dtypes
pokemon.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [9]:
#column names
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [10]:
#summary statistics
pokemon.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [12]:
#What is the highest HP value present?
pokemon['HP'].max()

255

In [77]:
#Create a function named highest_attack.

def highest_attack(x):
    return pokemon['Attack'].max()

In [79]:
#Use the loaded dataframe as an argument.
highest_attack(pokemon)

190

In [13]:
#Which Pokemon possess(es) the highest HP value?
pokemon[pokemon['HP'] == pokemon['HP'].max()]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False

In [18]:
#How many different types are represented in Type 1?
pokemon.groupby('Type 1').nunique()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,63,69,11,22,41,32,31,31,33,6,1
Dark,28,31,8,20,17,21,22,18,23,5,2
Dragon,24,32,7,19,21,15,18,18,19,5,2
Electric,36,44,10,18,22,24,24,24,25,6,2
Fairy,17,17,1,15,14,15,15,14,16,4,2
Fighting,25,27,4,19,18,16,16,15,21,6,1
Fire,47,52,9,27,36,29,31,26,29,6,2
Flying,3,4,1,3,4,3,4,3,4,2,2
Ghost,23,32,6,20,20,22,21,20,25,6,2
Grass,66,70,10,25,37,30,40,29,38,6,2
Ground,30,32,9,20,25,21,18,16,23,5,2
Ice,23,24,5,13,16,14,17,16,16,6,2
Normal,93,98,7,42,39,41,39,43,44,6,2
Poison,28,28,7,21,23,24,16,20,20,6,1
Psychic,47,57,7,28,30,27,32,25,34,6,2
Rock,41,44,12,23,31,27,28,26,27,6,2
Steel,22,27,8,13,18,19,16,19,14,5,2
Water,105,112,14,41,52,42,50,40,43,6,2

In [81]:
#Create a function named num_types
def num_types(x):
    return pokemon['Type 1'].nunique()

In [82]:
#Use the loaded dataframe as an argument
num_types(pokemon)

18

In [20]:
#Number of Pokemon whose Type 2 is Ghost
len(pokemon[pokemon['Type 2']=='Ghost'])

14

In [102]:
#Percentage of Pokemon whose Type 2 is Ghost
ghost_bois = len(pokemon[(pokemon['Type 1']== 'Ghost') | (pokemon['Type 2']== 'Ghost')])
round((ghost_bois / len(pokemon)) * 100, 2)

5.75

In [101]:
pokemon[(pokemon['Type 1']== 'Ghost') | (pokemon['Type 2']== 'Ghost')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
215,200,Misdreavus,Ghost,NaN,60,60,60,85,85,85,2,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
326,302,Sableye,Dark,Ghost,50,75,75,65,65,50,3,False
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False
385,353,Shuppet,Ghost,NaN,44,75,35,63,33,45,3,False
386,354,Banette,Ghost,NaN,64,115,65,83,63,65,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False
389,356,Dusclops,Ghost,NaN,40,70,130,60,130,25,3,False
472,425,Drifloon,Ghost,Flying,90,50,34,60,44,70,4,False
473,426,Drifblim,Ghost,Flying,150,80,44,90,54,80,4,False
477,429,Mismagius,Ghost,NaN,60,60,60,105,105,105,4,False
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4,False
529,477,Dusknoir,Ghost,NaN,45,100,135,65,135,45,4,False
530,478,Froslass,Ice,Ghost,70,80,70,80,70,110,4,False
531,479,Rotom,Electric,Ghost,50,50,77,95,77,91,4,False
544,487,GiratinaAltered Forme,Ghost,Dragon,150,100,120,100,120,90,4,True
545,487,GiratinaOrigin Forme,Ghost,Dragon,150,120,100,120,100,90,4,True
623,562,Yamask,Ghost,NaN,38,30,85,55,65,30,5,False
624,563,Cofagrigus,Ghost,NaN,58,50,145,95,105,30,5,False
653,592,Frillish,Water,Ghost,55,40,50,65,85,40,5,False
654,593,Jellicent,Water,Ghost,100,60,70,85,105,60,5,False
668,607,Litwick,Ghost,Fire,50,30,55,65,55,20,5,False
669,608,Lampent,Ghost,Fire,60,40,60,95,60,55,5,False
670,609,Chandelure,Ghost,Fire,60,55,90,145,90,80,5,False
683,622,Golett,Ground,Ghost,59,74,50,35,50,35,5,False
684,623,Golurk,Ground,Ghost,89,124,80,55,80,55,5,False
748,679,Honedge,Steel,Ghost,45,80,100,35,37,28,6,False
749,680,Doublade,Steel,Ghost,59,110,150,45,49,35,6,False
750,681,AegislashBlade Forme,Steel,Ghost,60,150,50,150,50,60,6,False
751,681,AegislashShield Forme,Steel,Ghost,60,50,150,50,150,60,6,False
778,708,Phantump,Ghost,Grass,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,85,100,122,58,75,54,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True

In [104]:
#Create a function named percent_ghost
def percent_ghost(df):
    ghost_bois = len(df[(df['Type 1']== 'Ghost') | (df['Type 2']== 'Ghost')])
    return round((ghost_bois / len(df)) * 100, 2)

In [105]:
#Use the loaded dataframe as an argument
percent_ghost(pokemon)

5.75

In [23]:
#Number of Pokemon whose Attack is greater than Defense
len(pokemon[pokemon['Attack'] > pokemon['Defense']])

433

In [69]:
#Lowest speed for Grass or Rock
grassrock1 = pokemon[pokemon['Type 1'].isin(['Grass', 'Rock'])]
grassrock2 = pokemon[pokemon['Type 2'].isin(['Grass', 'Rock'])]

grassrock1.min(), grassrock2.min()
pokemon[pokemon['Speed']== 5]

/var/folders/qf/t052sdrx70bffjpl89m9_hz00000gn/T/ipykernel_96250/1416403884.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  grassrock1.min(), grassrock2.min()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
495,446,Munchlax,Normal,NaN,135,85,40,40,85,5,4,False

In [106]:
grassrock1 = pokemon[pokemon['Type 1'].isin(['Grass', 'Rock'])]['Speed'].min()
grassrock2 = pokemon[pokemon['Type 2'].isin(['Grass', 'Rock'])]['Speed'].min()
grassrock2

5

In [108]:
#Average speed by Generation
pokemon.groupby('Generation').Speed.mean()

Generation
1    72.584337
2    61.811321
3    66.925000
4    71.338843
5    68.078788
6    66.439024
Name: Speed, dtype: float64